routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;



Auth::routes();



Route::get('/', 'HomeController@index')->name('home');

//Route::get('lang/{language}', 'LanguageController@switchLang')->name('lang.switch');

Route::group(['prefix' => 'administrator' , 'namespace' => 'Admin'], function () {

    Route::get('/login', 'LoginController@login')->name('admin.login');
    Route::post('/login', 'LoginController@postLogin')->name('admin.postLogin');

    // Password Reset Routes...

    Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('administrator.password.request');
    Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('administrator.password.email');
    Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('administrator.password.reset.token');
    Route::post('password/reset', 'Auth\ResetPasswordController@reset');

});


Route::group(['prefix' => 'administrator', 'namespace' => 'Admin', 'middleware' => ['admin']], function () {

    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/home', 'HomeController@index')->name('admin.home');


    Route::resource('helpAdmin', 'HelpAdminController');
    Route::get('helpAdmin/{id}/delete', 'HelpAdminController@delete')->name('helpAdmin.delete');
    Route::post('helpAdmin/{id}/delete', 'HelpAdminController@deleteHelpAdmin')->name('helpAdmin.message.delete');
    Route::post('helpAdmin/{id}/suspend', 'HelpAdminController@suspendHelpAdmin')->name('helpAdmin.message.suspend');
    Route::get('user/{id}/delete', 'UsersController@delete')->name('user.for.delete');
    Route::post('user/suspend', 'HelpAdminController@suspend')->name('user.suspend');
    // Roles routes ..........
    Route::resource('roles', 'RolesController');
    Route::post('role/delete', 'RolesController@delete')->name('role.delete');


    Route::resource('users', 'UsersController');
    Route::resource('providers_app', 'ProviderController');
    Route::post('providers_app/suspend', 'ProviderController@suspend')->name('providers_app.suspend');
    Route::post('accepted','UsersController@accpetedUser')->name('user.accepted');
    Route::post('refuseUser','UsersController@refuseUser')->name('user.refuseUser');
    Route::post('reAcceptUser','UsersController@reAcceptUser')->name('user.reAcceptUser');
    Route::post('suspendUser','UsersController@suspendUser')->name('user.suspendUser');

    Route::resource('deliveries', 'DeliveryController');
    Route::post('deliveries/accepted','DeliveryController@accpetedUser')->name('deliveries.accepted');
    Route::post('deliveries/refuseUser','DeliveryController@refuseUser')->name('deliveries.refuseUser');

    Route::resource('supplies', 'SuppliesController');
    Route::post('supplies/delete', 'SuppliesController@delete')->name('supplies.delete');
    Route::post('supplies/delete_image', 'SuppliesController@deleteImage')->name('supplies.deleteImage');

    Route::resource('pets', 'PetController');
    Route::resource('plants', 'PlantController');
    Route::post('pets/suspend', 'PetController@suspend')->name('pets.suspend');


    Route::resource('cultural_videos', 'CulturalVideoController');
    Route::post('cultural_videos/suspend', 'CulturalVideoController@suspend')->name('cultural_videos.suspend');
    Route::post('cultural_videos/delete', 'CulturalVideoController@delete')->name('cultural_videos.delete');


    Route::get('public/notifications', 'NotificationsController@publicNotifications')->name('public.notifications');
    Route::get('public/notifications/create', 'NotificationsController@createPublicNotifications')->name('create.public.notifications');

    Route::get('notifications/promo_code', 'NotificationsController@promo_code')->name('notifications_admin.promo_code');
    Route::get('notifications/get_promo_code', 'NotificationsController@get_promo_code')->name('notifications_admin.get_promo_code');
    Route::get('notifications/renderUsesData', 'NotificationsController@renderUsesData')->name('notifications_admin.renderUsesData');
    Route::post('notifications_admin/send_promo_code', 'NotificationsController@send_promo_code')->name('notifications_admin.send_promo_code');
    Route::post('notifications_admin/delete', 'NotificationsController@delete')->name('notifications_admin.delete');

    Route::post('send/public/notifications', 'NotificationsController@sendPublicNotifications')->name('send.public.notifications');


    // --------------------------------------  promo_codes .................
    Route::resource('promo_codes', 'PromoCodesController');
    Route::post('promo_codes/delete', 'PromoCodesController@delete')->name('promo_codes.delete');
    Route::post('promo_codes/suspend', 'PromoCodesController@suspend')->name('promo_codes.suspend');


    Route::get('settings/aboutus', 'SettingsController@aboutus')->name('settings.aboutus');
    Route::get('settings/taxs', 'SettingsController@taxs')->name('settings.taxs');
    Route::get('settings/termsProvider', 'SettingsController@termsGym')->name('settings.termsGym');
    Route::get('settings/terms', 'SettingsController@terms')->name('settings.terms');
    Route::get('settings/suspendElement', 'SettingsController@suspendElement')->name('settings.suspendElement');

    Route::get('/settings/app-general-settings', 'SettingsController@appGeneralSettings')->name('settings.app.general');
    Route::get('settings/contacts', 'SettingsController@contactus')->name('settings.contactus');
    Route::get('settings/minutes_control', 'SettingsController@minutes_control')->name('settings.minutes_control');


    Route::post('/settings', 'SettingsController@store')->name('administrator.settings.store');

//    Route::post('contactus/reply/{id}', 'SupportsController@reply')->name('support.reply');
//    Route::get('contactus', 'SupportsController@index')->name('support.index');
//    Route::get('contactus/{id}', 'SupportsController@show')->name('support.show');
//    Route::post('support/contact/delete', 'SupportsController@delete')->name('support.contact.delete');


//    Route::resource('supports', 'SupportsController');
//    Route::post('supports/delete', 'SupportsController@delete')->name('supports.delete');

//    Route::resource('types', 'TypesSupportController');


    Route::post('city/delete/group', 'CitiesController@groupDelete')->name('cities.group.delete');
    Route::post('cities/delete', 'CitiesController@delete')->name('city.delete');
    Route::resource('cities', 'CitiesController');
    Route::post('city/suspend', 'CitiesController@suspend')->name('city.suspend');

    // -------------------------------------- categories .................
    Route::resource('categories', 'CategoriesController');
    Route::post('categories/delete', 'CategoriesController@delete')->name('categories.delete');
    Route::post('categories/suspend', 'CategoriesController@suspend')->name('categories.suspend');

    Route::resource('reports', 'ReportsController');

    Route::get('/testImageView', 'UsersController@testImageView')->name('Provider.testImageView');
    Route::post('/testImage', 'UsersController@testImage')->name('Provider.testImage');


    Route::resource('banks', 'BanksController');
    Route::post('bank/suspend', 'BanksController@suspend')->name('bank.suspend');

    Route::get('bank-transfer-admin', 'BankTransferController@index')->name('bank-transfer-admin');
    Route::post('accept-transfer-admin', 'BankTransferController@accepted')->name('accept-transfer-admin');
    Route::post('refuse-transfer-admin', 'BankTransferController@refuse')->name('refuse-transfer-admin');

    Route::resource('admin_contact_us_inbox', 'ContactUsController');
    Route::get("admin_reports","ContactUsController@reports")->name("admin.support.reports");
    Route::get('updateIsRead', 'ContactUsController@updateIsRead')->name('admin.support.updateIsRead');
    Route::get('updateIsDeleted', 'ContactUsController@updateIsDeleted')->name('admin.support.updateIsDeleted');
    Route::get('removeAllMessages', 'ContactUsController@removeAllMessages')->name('admin.support.removeAllMessages');


    Route::resource('BankProjects', 'BankProjectsController');
    Route::post('BankProjects/accepted', 'BankProjectsController@accepted')->name('BankProjects.accepted');
    Route::post('BankProjects/refuse', 'BankProjectsController@refuse')->name('BankProjects.refuse');

    Route::resource('reports', 'ReportsController');
    Route::get('provider_data_report', 'ReportsController@gym_data')->name('provider_data_report');

    Route::post('/logout', 'LoginController@logout')->name('administrator.logout');

});



Route::get('/sub', function (Illuminate\Http\Request $request) {

    $cities =\App\Models\City::whereParentId($request->id)->get();

    if (!empty($cities) && count($cities) > 0){
        return response()->json( $cities);
    }else{

        return response()->json(401);
    }


})->name('getSub');



Route::get('roles', function () {

    $user = Auth::guard('master_user')->user();
//    $user->retract('admin');
    $user->assign('*');
    Bouncer::allow('*')->everything();
    $user->allow('users_manage');
});


Route::post('user/update/token', function (Illuminate\Http\Request $request) {

    $user = \App\User::whereId($request->id)->first();

    if ($request->token) {
        $data = \App\Models\Device::where('device', $request->token)->first();
        if ($data) {
            $data->user_id = $user->id;
            $data->save();
        } else {


            $data = new \App\Models\Device;
            $data->device = $request->token;
            $data->user_id = $user->id;
            $data->device_type = 'web';
            $data->save();
        }
    }

})->name('user.update.token');



Route::get('testing',function (){
    $data = [];
    $data[] =  env('DB_DATABASE');
    $data[] =  env('DB_USERNAME');
    $data[] =  env('DB_PASSWORD');

resources/views/admin/layouts/_partials/footer.blade.php
</div>
<!-- end container -->

<!-- Right Sidebar -->
<div class="side-bar right-bar">
    <a href="javascript:void(0);" class="right-bar-toggle">
        <i class="zmdi zmdi-close-circle-o"></i>
    </a>
    <h4 class="">Notifications</h4>
    <div class="notification-list nicescroll">
        <ul class="list-group list-no-border user-list">
            <li class="list-group-item">
                <a href="#" class="user-list-item">
                    <div class="avatar">
                        <img src="assets/images/users/avatar-2.jpg" alt="">
                    </div>
                    <div class="user-desc">
                        <span class="name">Michael Zenaty</span>
                        <span class="desc">There are new settings available</span>
                        <span class="time">2 hours ago</span>
                    </div>
                </a>
            </li>
            <li class="list-group-item">
                <a href="#" class="user-list-item">
                    <div class="icon bg-info">
                        <i class="zmdi zmdi-account"></i>
                    </div>
                    <div class="user-desc">
                        <span class="name">New Signup</span>
                        <span class="desc">There are new settings available</span>
                        <span class="time">5 hours ago</span>
                    </div>
                </a>
            </li>
            <li class="list-group-item">
                <a href="#" class="user-list-item">
                    <div class="icon bg-pink">
                        <i class="zmdi zmdi-comment"></i>
                    </div>
                    <div class="user-desc">
                        <span class="name">New Message received</span>
                        <span class="desc">There are new settings available</span>
                        <span class="time">1 day ago</span>
                    </div>
                </a>
            </li>
            <li class="list-group-item active">
                <a href="#" class="user-list-item">
                    <div class="avatar">
                        <img src="assets/images/users/avatar-3.jpg" alt="">
                    </div>
                    <div class="user-desc">
                        <span class="name">James Anderson</span>
                        <span class="desc">There are new settings available</span>
                        <span class="time">2 days ago</span>
                    </div>
                </a>
            </li>
            <li class="list-group-item active">
                <a href="#" class="user-list-item">
                    <div class="icon bg-warning">
                        <i class="zmdi zmdi-settings"></i>
                    </div>
                    <div class="user-desc">
                        <span class="name">Settings</span>
                        <span class="desc">There are new settings available</span>
                        <span class="time">1 day ago</span>
                    </div>
                </a>
            </li>

        </ul>
    </div>
</div>
<!-- /Right-bar -->
</div>

resources/views/admin/layouts/_partials/header.blade.php
<!-- Navigation Bar-->
<header id="topnav">

    <div class="topbar-main">
        <div class="container">

            <!-- LOGO -->
            <div class="topbar-left">
                {{--<a href="{{ route('admin.home') }}" class="logo" style="width: 150px;">--}}
                    {{--<img style="width: 100%" src="{{ request()->root() }}/public/assets/admin/images/logo.png"></a>--}}
            </div>
            <!-- End Logo container-->


            <div class="menu-extras">

                <ul class="nav navbar-nav navbar-right pull-right">
                    {{--<li>--}}
                    {{--<forsm role="search" class="navbar-left app-search pull-left hidden-xs">--}}
                    {{--<input type="text" placeholder="بحث ..." class="form-control">--}}
                    {{--<a href=""><i class="fa fa-search"></i></a>--}}
                    {{--</form>--}}
                    {{--</li>--}}

                    <li>
                        <!-- Notification -->
                        <div class="notification-box">
                            <ul class="list-inline m-b-0">
                                <li>
                                    <a href="javascript:void(0);" class="right-bar-toggle">
                                        <i class="zmdi zmdi-notifications-none"></i>
                                    </a>
                                    <div class="noti-dot">
                                        <span class="dot"></span>
                                        <span class="pulse"></span>
                                    </div>
                                </li>

                            </ul>
                        </div>
                        <!-- End Notification bar -->
                    </li>


                    <li class="dropdown user-box">
                        <a href="" class="dropdown-toggle waves-effect waves-light profile " data-toggle="dropdown"
                           aria-expanded="true">

                            @if(isset($helper))
                                @if($master_user->admin)
                                    <img src="{{  $helper->getDefaultImage(URL('/').'/'. optional($master_user->admin)->image ,'/assets/admin/images/default.png') }}"
                                         alt="user-img" class="img-circle user-img">
                                @else
                                    <img src="{{  $helper->getDefaultImage(URL('/').'/'. optional($master_user->helper_admin)->image,'/assets/admin/images/default.png') }}"
                                         alt="user-img" class="img-circle user-img">
                                @endif

                            @endif
                        </a>

                        <ul class="dropdown-menu">
                            <li><a href="{{ route('helpAdmin.edit', $master_user->id)}}"><i
                                            class="ti-user m-r-5"></i>@lang('maincp.personal_page')</a></li>
{{--                            <!--<li><a href="{{ route('users.edit', auth()->id()) }}"><i class="ti-settings m-r-5"></i>-->--}}
                            <!--        @lang('global.settings')-->
                            <!--    </a>-->
                            <!--</li>-->
                            <li><a href="{{ route('logout') }}"
                                   onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                                    <i class="ti-power-off m-r-5"></i>@lang('maincp.log_out')
                                </a>
                            </li>
                        </ul>
                    </li>
                </ul>
                <div class="menu-item">
                    <!-- Mobile menu toggle-->
                    <a class="navbar-toggle">
                        <div class="lines">
                            <span></span>
                            <span></span>
                            <span></span>
                        </div>
                    </a>
                    <!-- End mobile menu toggle-->
                </div>
            </div>

        </div>
    </div>

    <form id="logout-form" action="{{ route('administrator.logout') }}" method="POST"
          style="display: none;">
        {{ csrf_field() }}
    </form>

    <div class="navbar-custom">
        <div class="container">
            <div id="navigation">
                <!-- Navigation Menu-->
                <ul class="navigation-menu" style="    font-size: 14px;">



                    @if(auth('master_user')->user()->checkIfHasAbility('statistics_manage'))
                        <li>
                            <a href="{{ route('admin.home') }}"><i class="zmdi zmdi-view-dashboard"></i>
                                <span> @lang('menu.home') </span> </a>
                        </li>
                    @endif

                    @if(auth('master_user')->user()->checkIfHasAbility('app_users_manage'))

                            <li class="has-submenu">
                                <a href="#"><i class="zmdi zmdi-layers"></i><span>  @lang('trans.managers_ctrl_panel') </span>
                                </a>
                                <ul class="submenu ">
                                    <li><a href="{{ route('helpAdmin.index') }}">  مساعدين مدير التطبيق </a></li>
                                    {{--                                @can('permission_manage')--}}
                                    <li>
                                        <a href="{{route('roles.index')}}">  @lang('trans.roles_and_permission')     </a>
                                    </li>
                                    {{--                                @endcan--}}

                                </ul>
                            </li>
                    @endif

                    @if(auth('master_user')->user()->checkIfHasAbility('users_manage'))

                        <li class="has-submenu">
                            <a href="{{ route('users.index') }}"><i
                                        class="zmdi zmdi-accounts"></i><span>إدارة المستخدمين   </span>
                            </a>
                        </li>

                    @endif


                        <li class="has-submenu">
                            <a href="#"><i class="zmdi zmdi-layers"></i><span>  إدارة المناديب   </span>
                            </a>
                            <ul class="submenu ">
                                <li><a href="{{ route('deliveries.index') }}?is_accepted=0"> طلبات جديدة    </a></li>
                                <li>  <a href="{{route('deliveries.index')}}">  المفعلين لدينا   </a>  </li>

                            </ul>
                        </li>

                        <li class="has-submenu">
                            <a href="#"><i class="zmdi zmdi-layers"></i><span>  إدارة الإضافات الخاصة بالتطبيق   </span>
                            </a>
                            <ul class="submenu ">
                                <li><a href="{{ route('cities.index') }}"> المدن  </a></li>
                                <li>  <a href="{{route('categories.index')}}">    الأقسام </a>  </li>
                                <li>  <a href="{{route('supplies.index')}}">    المستلزمات </a>  </li>
                                <li>  <a href="{{route('plants.index')}}">    النباتات </a>  </li>
                                <li>  <a href="{{route('pets.index')}}">    الحيوانات </a>  </li>
                                <li>  <a href="{{route('cultural_videos.index')}}">    فيديوهات ثقافية </a>  </li>
                                <li>  <a href="{{route('promo_codes.index')}}">   كوبونات الخصم </a>  </li>
                                <li>  <a href="{{ route('notifications_admin.promo_code') }}"> إرسال  كوبونات الخصم </a>  </li>


                            </ul>
                        </li>

                        @if(auth('master_user')->user()->checkIfHasAbility('settings_manage'))

                            <li class="has-submenu">
                                <a href="#"><i class="zmdi zmdi-settings"></i><span>@lang('maincp.setting')<i
                                            class="fa fa-arrow-down visible-xs" aria-hidden="true"></i></span> </a>
                                <ul class="submenu">
                                    <li><a href="{{ route('settings.contactus') }}">@lang('trans.general_setting_app')</a>    </li>
                                    <li><a href="{{ route('settings.minutes_control') }}">التحكم في الوقت الخاص بالعروض </a>    </li>
                                    <li><a href="{{ route('settings.aboutus') }}">@lang('trans.about_app')</a>   </li>
                                    <li><a href="{{ route('settings.terms') }}">@lang('trans.terms') </a></li>
{{--                                    <li><a href="{{ route('banks.index') }}"> الحسابات البنكية </a></li>--}}
{{--                                    <li><a href="{{ route('bank-transfer-admin') }}"> إدارة التحويلات البنكية  </a></li>--}}
{{--                                    <li><a href="{{ route('public.notifications') }}"> الإشعارات الجماعية      </a></li>--}}
                                    <li><a href="{{ route('admin_contact_us_inbox.index') }}">  تواصل معنا     </a></li>
                                    <li><a href="{{ route('admin.support.reports') }}"> البلاغات   </a></li>
                                </ul>
                            </li>
                    @endif

                        <li class="has-submenu">

                            <a href="{{route("reports.index")}}"><i class="zmdi zmdi-settings"></i><span>إدارة الطلبات
                                    <i  class="fa fa-arrow-down visible-xs" aria-hidden="true"></i></span>
                            </a>
                            <ul class="submenu">
                                <li><a href="{{ route('reports.index') }}?type=pets">طلبات الحيوانات</a>    </li>
                                <li><a href="{{ route('reports.index') }}?type=pets_supplies">طلبات مستلزمات الحيوانات </a>    </li>
                                <li><a href="{{ route('reports.index') }}?type=plants">طلبات النباتات </a>    </li>
                                <li><a href="{{ route('reports.index') }}?type=plants_supplies">طلبات مستلزمات النباتات </a>    </li>
                            </ul>
                        </li>
                        </li>

                </ul>
                <!-- End navigation menu  -->
            </div>
        </div>
    </div>

</header>
<!-- End Navigation Bar-->


<div class="wrapper">
    <div class="container">

resources/views/admin/layouts/_partials/scripts.blade.php
<!-- jQuery  -->
<script src="/assets/admin/js/jquery.min.js"></script>
<script src="/assets/admin/js/bootstrap-rtl.min.js"></script>
<script src="/assets/admin/js/detect.js"></script>
<script src="/assets/admin/js/fastclick.js"></script>

<script src="/assets/admin/js/jquery.slimscroll.js"></script>
<script src="/assets/admin/js/jquery.blockUI.js"></script>
<script src="/assets/admin/js/waves.js"></script>
<script src="/assets/admin/js/wow.min.js"></script>
<script src="/assets/admin/js/jquery.nicescroll.js"></script>
<script src="/assets/admin/js/jquery.scrollTo.min.js"></script>

<!-- KNOB JS -->
<!--[if IE]>
<script type="text/javascript"
        src="/assets/admin/plugins/jquery-knob/excanvas.js"></script>
<![endif]-->
<script src="/assets/admin/plugins/jquery-knob/jquery.knob.js"></script>


<!-- responsive-table-->
<script src="/assets/admin/plugins/RWD-Table-Patterns/dist/js/rwd-table.min.js"
        type="text/javascript"></script>


<!-- Dashboard init -->
<script src="/assets/admin/pages/jquery.dashboard.js"></script>


<!-- file uploads js -->
<!--<script src="/assets/admin/plugins/fileuploads/js/dropify.min.js"></script>-->
<script src="https://jeremyfagis.github.io/dropify/dist/js/dropify.js"></script>
<!-- Validation js (Parsleyjs) -->
<script type="text/javascript"
        src="/assets/admin/plugins/parsleyjs/dist/parsley.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.2.5/jquery.fancybox.min.js"></script>

<script src="/assets/admin/plugins/toastr/toastr.min.js"></script>

<script src="/assets/admin/plugins/switchery/switchery.min.js"></script>
<script src="/assets/admin/plugins/waypoints/lib/jquery.waypoints.js"></script>
<script src="/assets/admin/plugins/counterup/jquery.counterup.min.js"></script>

<script type="text/javascript"
        src="/assets/admin/plugins/multiselect/js/jquery.multi-select.js"></script>

<script src="/assets/admin/plugins/ckeditor/ckeditor.js"></script>
<script src="/assets/admin/plugins/ckeditor/samples/js/sample.js"></script>

<!-- Sweet Alert js -->
<script src="/assets/admin/plugins/bootstrap-sweetalert/sweet-alert.min.js"></script>
<script src="/assets/admin/pages/jquery.sweet-alert.init.js"></script>


<!-- App js -->
<script src="/assets/admin/js/jquery.core.js"></script>
<script src="/assets/admin/js/jquery.app.js"></script>
<script src="/assets/admin/js/validate-ar.js"></script>

<!-- Datatables-->
<script src="/assets/admin/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="/assets/admin/plugins/datatables/dataTables.bootstrap.js"></script>
<script src="/assets/admin/plugins/datatables/dataTables.buttons.min.js"></script>
<script src="/assets/admin/plugins/datatables/buttons.bootstrap.min.js"></script>
<script src="/assets/admin/plugins/datatables/jszip.min.js"></script>
<script src="/assets/admin/plugins/datatables/pdfmake.min.js"></script>
<script src="/assets/admin/plugins/datatables/vfs_fonts.js"></script>
<script src="/assets/admin/plugins/datatables/buttons.html5.min.js"></script>
<script src="/assets/admin/plugins/datatables/buttons.print.min.js"></script>
<script src="/assets/admin/plugins/datatables/dataTables.fixedHeader.min.js"></script>
<script src="/assets/admin/plugins/datatables/dataTables.keyTable.min.js"></script>
<script src="/assets/admin/plugins/datatables/dataTables.responsive.min.js"></script>
<script src="/assets/admin/plugins/datatables/responsive.bootstrap.min.js"></script>
<script src="/assets/admin/plugins/datatables/dataTables.scroller.min.js"></script>


<!-- Datatable init js -->
<script src="/assets/admin/pages/datatables.init.js"></script>
{{--<script src="/assets/admin/js/examples.min.js"> </script>--}}

<!-- Toastr js -->
<script src="/assets/admin/plugins/toastr/toastr.min.js"></script>
<script src="/assets/admin/plugins/summernote/dist/summernote.min.js"></script>

<!-- Modal-Effect -->
<script src="/assets/admin/plugins/custombox/dist/custombox.min.js"></script>
<script src="/assets/admin/plugins/custombox/dist/legacy.min.js"></script>


<script src="/assets/admin/plugins/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>

<script>
    $('body').delegate('.numbersOnly', 'keyup keypress', function (event) {

        var limit = $(this).attr('data-limit');
        var message = $(this).attr('data-message');
        var field = $(this).attr('name');

        if (!limit) {
            limit = 25;
        }

        if (this.value.length > limit) {
            $(this).css({
                'border': '1px solid red',
                'font-size': '14px',
                'color': 'red'
            });

            /****Not Work yet****/

            $('.' + field).css({
                'font-size': '12px'
            });

            $('.' + field).html(message);




        } else {
            $(this).removeAttr('style');
            $('.' + field).html('');

        }


        // if (!Number(this.value)) {
        //     this.value = this.value.replace(/[^0-9\.]/g, '');
        //     event.preventDefault();
        //     return false;
        // }


        if (this.value.length > limit) {

            this.value = this.value.replace(/[^0-9\.]/g, '');
            if(!Number(this.value)){
                $('.' + field).html(message);
            }
            event.preventDefault();
            return false;
        }

        this.value = this.value.replace(/[^0-9\.]/g, '');
    });
</script>

@yield('scripts')
<script>

    // Date Picker
    //    jQuery('.datepicker').datepicker();

    //    jQuery('.datepicker-autoclose').datepicker({
    //        autoclose: true,
    //        todayHighlight: true
    //    });

    $('.datepicker').datepicker({format: 'yyyy-mm-dd',autoclose: true,todayHighlight: true});
    initSample();

    //    TableManageButtons.init();


</script>