routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;



Auth::routes();



Route::get('/', 'HomeController@index')->name('home');

//Route::get('lang/{language}', 'LanguageController@switchLang')->name('lang.switch');

Route::group(['prefix' => 'administrator' , 'namespace' => 'Admin'], function () {

    Route::get('/login', 'LoginController@login')->name('admin.login');
    Route::post('/login', 'LoginController@postLogin')->name('admin.postLogin');

    // Password Reset Routes...

    Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('administrator.password.request');
    Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('administrator.password.email');
    Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('administrator.password.reset.token');
    Route::post('password/reset', 'Auth\ResetPasswordController@reset');

});


Route::group(['prefix' => 'administrator', 'namespace' => 'Admin', 'middleware' => ['admin']], function () {

    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/home', 'HomeController@index')->name('admin.home');


    Route::resource('helpAdmin', 'HelpAdminController');
    Route::get('helpAdmin/{id}/delete', 'HelpAdminController@delete')->name('helpAdmin.delete');
    Route::post('helpAdmin/{id}/delete', 'HelpAdminController@deleteHelpAdmin')->name('helpAdmin.message.delete');
    Route::post('helpAdmin/{id}/suspend', 'HelpAdminController@suspendHelpAdmin')->name('helpAdmin.message.suspend');
    Route::get('user/{id}/delete', 'UsersController@delete')->name('user.for.delete');
    Route::post('user/suspend', 'HelpAdminController@suspend')->name('user.suspend');
    // Roles routes ..........
    Route::resource('roles', 'RolesController');
    Route::post('role/delete', 'RolesController@delete')->name('role.delete');


    Route::resource('users', 'UsersController');
    Route::resource('providers_app', 'ProviderController');
    Route::post('providers_app/suspend', 'ProviderController@suspend')->name('providers_app.suspend');
    Route::post('accepted','UsersController@accpetedUser')->name('user.accepted');
    Route::post('refuseUser','UsersController@refuseUser')->name('user.refuseUser');
    Route::post('reAcceptUser','UsersController@reAcceptUser')->name('user.reAcceptUser');
    Route::post('suspendUser','UsersController@suspendUser')->name('user.suspendUser');

    Route::resource('deliveries', 'DeliveryController');
    Route::post('deliveries/accepted','DeliveryController@accpetedUser')->name('deliveries.accepted');
    Route::post('deliveries/refuseUser','DeliveryController@refuseUser')->name('deliveries.refuseUser');

    Route::resource('supplies', 'SuppliesController');
    Route::post('supplies/delete', 'SuppliesController@delete')->name('supplies.delete');
    Route::post('supplies/delete_image', 'SuppliesController@deleteImage')->name('supplies.deleteImage');

    Route::resource('pets', 'PetController');
    Route::resource('plants', 'PlantController');
    Route::post('pets/suspend', 'PetController@suspend')->name('pets.suspend');


    Route::resource('cultural_videos', 'CulturalVideoController');
    Route::post('cultural_videos/suspend', 'CulturalVideoController@suspend')->name('cultural_videos.suspend');
    Route::post('cultural_videos/delete', 'CulturalVideoController@delete')->name('cultural_videos.delete');


    Route::get('public/notifications', 'NotificationsController@publicNotifications')->name('public.notifications');
    Route::get('public/notifications/create', 'NotificationsController@createPublicNotifications')->name('create.public.notifications');

    Route::get('notifications/promo_code', 'NotificationsController@promo_code')->name('notifications_admin.promo_code');
    Route::get('notifications/get_promo_code', 'NotificationsController@get_promo_code')->name('notifications_admin.get_promo_code');
    Route::get('notifications/renderUsesData', 'NotificationsController@renderUsesData')->name('notifications_admin.renderUsesData');
    Route::post('notifications_admin/send_promo_code', 'NotificationsController@send_promo_code')->name('notifications_admin.send_promo_code');
    Route::post('notifications_admin/delete', 'NotificationsController@delete')->name('notifications_admin.delete');

    Route::post('send/public/notifications', 'NotificationsController@sendPublicNotifications')->name('send.public.notifications');


    // --------------------------------------  promo_codes .................
    Route::resource('promo_codes', 'PromoCodesController');
    Route::post('promo_codes/delete', 'PromoCodesController@delete')->name('promo_codes.delete');
    Route::post('promo_codes/suspend', 'PromoCodesController@suspend')->name('promo_codes.suspend');


    Route::get('settings/aboutus', 'SettingsController@aboutus')->name('settings.aboutus');
    Route::get('settings/taxs', 'SettingsController@taxs')->name('settings.taxs');
    Route::get('settings/termsProvider', 'SettingsController@termsGym')->name('settings.termsGym');
    Route::get('settings/terms', 'SettingsController@terms')->name('settings.terms');
    Route::get('settings/suspendElement', 'SettingsController@suspendElement')->name('settings.suspendElement');

    Route::get('/settings/app-general-settings', 'SettingsController@appGeneralSettings')->name('settings.app.general');
    Route::get('settings/contacts', 'SettingsController@contactus')->name('settings.contactus');
    Route::get('settings/minutes_control', 'SettingsController@minutes_control')->name('settings.minutes_control');


    Route::post('/settings', 'SettingsController@store')->name('administrator.settings.store');

//    Route::post('contactus/reply/{id}', 'SupportsController@reply')->name('support.reply');
//    Route::get('contactus', 'SupportsController@index')->name('support.index');
//    Route::get('contactus/{id}', 'SupportsController@show')->name('support.show');
//    Route::post('support/contact/delete', 'SupportsController@delete')->name('support.contact.delete');


//    Route::resource('supports', 'SupportsController');
//    Route::post('supports/delete', 'SupportsController@delete')->name('supports.delete');

//    Route::resource('types', 'TypesSupportController');


    Route::post('city/delete/group', 'CitiesController@groupDelete')->name('cities.group.delete');
    Route::post('cities/delete', 'CitiesController@delete')->name('city.delete');
    Route::resource('cities', 'CitiesController');
    Route::post('city/suspend', 'CitiesController@suspend')->name('city.suspend');

    // -------------------------------------- categories .................
    Route::resource('categories', 'CategoriesController');
    Route::post('categories/delete', 'CategoriesController@delete')->name('categories.delete');
    Route::post('categories/suspend', 'CategoriesController@suspend')->name('categories.suspend');

    Route::resource('reports', 'ReportsController');

    Route::get('/testImageView', 'UsersController@testImageView')->name('Provider.testImageView');
    Route::post('/testImage', 'UsersController@testImage')->name('Provider.testImage');


    Route::resource('banks', 'BanksController');
    Route::post('bank/suspend', 'BanksController@suspend')->name('bank.suspend');

    Route::get('bank-transfer-admin', 'BankTransferController@index')->name('bank-transfer-admin');
    Route::post('accept-transfer-admin', 'BankTransferController@accepted')->name('accept-transfer-admin');
    Route::post('refuse-transfer-admin', 'BankTransferController@refuse')->name('refuse-transfer-admin');

    Route::resource('admin_contact_us_inbox', 'ContactUsController');
    Route::get("admin_reports","ContactUsController@reports")->name("admin.support.reports");
    Route::get('updateIsRead', 'ContactUsController@updateIsRead')->name('admin.support.updateIsRead');
    Route::get('updateIsDeleted', 'ContactUsController@updateIsDeleted')->name('admin.support.updateIsDeleted');
    Route::get('removeAllMessages', 'ContactUsController@removeAllMessages')->name('admin.support.removeAllMessages');


    Route::resource('BankProjects', 'BankProjectsController');
    Route::post('BankProjects/accepted', 'BankProjectsController@accepted')->name('BankProjects.accepted');
    Route::post('BankProjects/refuse', 'BankProjectsController@refuse')->name('BankProjects.refuse');

    Route::resource('reports', 'ReportsController');
    Route::get('provider_data_report', 'ReportsController@gym_data')->name('provider_data_report');

    Route::post('/logout', 'LoginController@logout')->name('administrator.logout');

});



Route::get('/sub', function (Illuminate\Http\Request $request) {

    $cities =\App\Models\City::whereParentId($request->id)->get();

    if (!empty($cities) && count($cities) > 0){
        return response()->json( $cities);
    }else{

        return response()->json(401);
    }


})->name('getSub');



Route::get('roles', function () {

    $user = Auth::guard('master_user')->user();
//    $user->retract('admin');
    $user->assign('*');
    Bouncer::allow('*')->everything();
    $user->allow('users_manage');
});


Route::post('user/update/token', function (Illuminate\Http\Request $request) {

    $user = \App\User::whereId($request->id)->first();

    if ($request->token) {
        $data = \App\Models\Device::where('device', $request->token)->first();
        if ($data) {
            $data->user_id = $user->id;
            $data->save();
        } else {


            $data = new \App\Models\Device;
            $data->device = $request->token;
            $data->user_id = $user->id;
            $data->device_type = 'web';
            $data->save();
        }
    }

})->name('user.update.token');



Route::get('testing',function (){
    $data = [];
    $data[] =  env('DB_DATABASE');
    $data[] =  env('DB_USERNAME');
    $data[] =  env('DB_PASSWORD');

app/Http/Controllers/Admin/PlantController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Pet;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class PlantController extends Controller
{
    public function index(){

        $pets = Pet::where('definition','plant')
            ->join('cities', 'pets.city_id', '=', 'cities.id')
            ->join('categories', 'pets.category_id', '=', 'categories.id')
//            ->join('colors', 'pets.color_id', '=', 'colors.id')
            ->join('users', 'pets.user_id', '=', 'users.id')
            ->join('master_users','users.master_user_id','=','master_users.id')
            ->select('pets.id','pets.name','price','quantity','weight','pets.is_suspend',
                'cities.name_ar as city_name' ,
                'categories.name_ar as category_name', 'master_users.phone as user_phone',
                DB::raw("(CASE WHEN (type = 'male') THEN 'ذكر' ELSE 'أنثي' END) as type")
            )
            ->where('is_deleted' , 0)
            ->get();


        $pageName  = 'النباتات';

        return view('admin.plant.index',compact('pets','pageName'));
    }
}

app/Http/Controllers/Api/User/PlantsController.php
<?php

namespace App\Http\Controllers\Api\User;

use App\Http\Controllers\Controller;
use App\Http\Requests\api\Pet\editVaild;
use App\Http\Requests\api\Plant\storePlantVaild;
use App\Http\Resources\Pets\PetsIndexResource;
use App\Http\Resources\Pets\PetsResource;
use App\Models\Pet;
use App\Traits\RespondsWithHttpStatus;
use Illuminate\Http\Request;

class PlantsController extends Controller
{
    use RespondsWithHttpStatus;

    private $petsRepository;

    public function __construct( )
    {
        $this->middleware('auth:api')->except(['show']);
    }

    public function index(Request  $request){

        $user = $request->user();

        $query =  Pet::whereDefinition('plant')->whereUserId($user->id)->where('is_deleted',0);

        $this->pagination_query($request, $query);

        return $this->success(' النباتات',PetsIndexResource::collection($query->get()) );
    }


    public function store(storePlantVaild $request){

        $data = $request->user()->pets()->create($request->validated());

        return $this->success('تم إضافة النبات بنجاح',new PetsResource($data));
    }

    public function edit(editVaild $request, $id){

        $plant = Pet::whereIsDeleted(0)->findOrFail($id);

        return $this->success('تم إعادة نشر النبات بنجاح',new PetsResource($plant));
    }

    public function destroy($id)
    {
        $plant = Pet::whereIsDeleted(0)->findOrFail($id);

        $plant->update(['is_deleted' => true]);

        return $this->success('تم مسح النبات بنجاح');
    }


    public function pagination_query($request ,$query ){
        $pageSize = $request->pageSize ?: 10;
        $skipCount = $request->skipCount;
        $currentPage = $request->get('take', 1); // Default to 1
        $query->skip($skipCount + (($currentPage - 1) * $pageSize));
        $query->take($pageSize);
        return $query->latest();
    }


}

resources/views/admin/plant/index.blade.php
@extends('admin.layouts.master')

@section('title', __('maincp.cities'))

@section('content')


    <!-- Page-Title -->
    <div class="row">
        <div class="col-sm-12">
            <div class="btn-group pull-right m-t-15 ">
                {{--                <a href="{{ route('supplies.create') }}"--}}
                {{--                   type="button" class="btn btn-custom waves-effect waves-light"--}}
                {{--                   aria-expanded="false">--}}
                {{--                <span class="m-l-5">--}}
                {{--                <i class="fa fa-plus"></i>--}}
                {{--                </span>--}}
                {{--                    إضافة حيوان--}}
                {{--                </a>--}}
            </div>
            <h4 class="page-title">{{$pageName}} </h4>
        </div>
    </div>



    <div class="row">
        <div class="col-sm-12">
            <div class="card-box table-responsive">

                <div class="dropdown pull-right">

                </div>

                <table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap"
                       cellspacing="0" width="100%">
                    <thead>
                    <tr>
                        <th>رقم النبات </th>
                        <th>اسم النبات </th>
                        <th>رقم تليفون صاحب النبات  </th>
                        <th>سعر النبات </th>
                        <th>  قسم النبات </th>
                        <th>مدينة النبات  </th>
                        <th>كمية النبات  </th>
                        <th>@lang('trans.status' ) </th>
                        <th>@lang('trans.options')</th>
                    </tr>
                    </thead>
                    <tbody>

                    @foreach($pets as $row)
                        <tr>

                            <td>{{ $row->id }}</td>
                            <td>{{ $row->name }}</td>
                            <td>{{ $row->user_phone }}</td>
                            <td>{{ $row->price }}</td>
                            <td>{{ $row->category_name }}</td>
                            <td>{{ $row->city_name }}</td>
                            <td>{{ $row->quantity }}</td>
                            <td>
                                <div class="StatusActive{{ $row->id }}"  style="display: {{ $row->is_suspend == 0 ? "none" : "block" }}; text-align: center;">
                                    <img  width="23px" src="{{ asset('assets/admin/images/false.png') }}" alt="">
                                </div>
                                <div class="StatusNotActive{{ $row->id }}" style="display: {{ $row->is_suspend == 0 ? "block" : "none" }};  text-align: center;">
                                    <img width="23px" src="{{ asset('assets/admin/images/ok.png') }}" alt="">
                                </div>

                            </td>
                            <td>


                                <a href="javascript:;"  data-id="{{ $row->id }}" data-type="0"
                                   data-url="{{ route('pets.suspend') }}"  style="@if($row->is_suspend == 0) display: none;  @endif"
                                   class="m-portlet__nav-link btn m-btn m-btn--hover-success m-btn--icon m-btn--icon-only m-btn--pill  suspendElement suspend{{ $row->id }}"
                                   id="suspendElement" data-message="تاكيد التفعيل"
                                   data-toggle="tooltip" data-placement="top"
                                   title="" data-original-title="فك الحظر ">
                                    <i class="fa fa-unlock"></i>
                                </a>

                                <a href="javascript:;"  data-id="{{ $row->id }}" data-type="1"
                                   data-url="{{ route('pets.suspend') }}" style="@if($row->is_suspend == 1) display: none;  @endif"
                                   class="m-portlet__nav-link btn m-btn m-btn--hover-danger m-btn--icon m-btn--icon-only m-btn--pill suspendElement unsuspend{{ $row->id }}"
                                   id="suspendElement"
                                   data-message="حظر"
                                   data-toggle="tooltip" data-placement="top"
                                   title="" data-original-title="{{ __('trans.suspend') }}">
                                    <i class="fa fa-lock"></i>
                                </a>

                                {{--                                <a href="{{ route('supplies.edit', $row->id) }}"--}}
                                {{--                                   data-toggle="tooltip" data-placement="top"--}}
                                {{--                                   data-original-title=" تعديل"--}}
                                {{--                                   class="btn btn-icon btn-xs waves-effect  btn-info">--}}
                                {{--                                    <i class="fa fa-edit"></i>--}}
                                {{--                                </a>--}}

                                {{--                                <a href="javascript:;" data-url="{{ route('supplies.delete') }}" id="elementRow{{ $row->id }}" data-id="{{ $row->id }}"--}}
                                {{--                                   class="removeElement btn btn-icon btn-trans btn-xs waves-effect waves-light btn-danger m-b-5">--}}
                                {{--                                    <i class="fa fa-remove"></i>--}}
                                {{--                                </a>--}}

                            </td>
                        </tr>
                    @endforeach

                    </tbody>
                </table>
            </div>
        </div><!-- end col -->
    </div>
    <!-- end row -->


@endsection


@section('scripts')



    <script src="/assets/admin/plugins/custombox/dist/custombox.min.js"></script>
    <script src="/assets/admin/plugins/custombox/dist/legacy.min.js"></script>
    <script>

        $('body').on('click', '.removeElement', function () {
            var id = $(this).attr('data-id');
            var url = $(this).attr('data-url');
            var $tr = $(this).closest($('#elementRow' + id).parent().parent());
            swal({
                title: "هل انت متأكد؟",
                text: "يمكنك استرجاع المحذوفات مرة اخرى لا تقلق.",
                type: "error",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "موافق",
                cancelButtonText: "إلغاء",
                confirmButtonClass: 'btn-danger waves-effect waves-light',
                closeOnConfirm: true,
                closeOnCancel: true,
            }, function (isConfirm) {
                if (isConfirm) {
                    $.ajax({
                        type: 'POST',
                        url: url,
                        data: {id: id},
                        dataType: 'json',
                        success: function (data) {

                            if (data.status == true) {
                                var shortCutFunction = 'success';
                                var msg = 'لقد تمت عملية الحذف بنجاح.';
                                var title = data.title;
                                toastr.options = {
                                    positionClass: 'toast-top-left',
                                    onclick: null
                                };
                                var $toast = toastr[shortCutFunction](msg, title); // Wire up an event handler to a button in the toast, if it exists
                                $toastlast = $toast;

                                $tr.find('td').fadeOut(1000, function () {
                                    $tr.remove();
                                });
                            }

                            if (data.status == false) {
                                var shortCutFunction = 'warning';
                                var msg =data.message;
                                var title = data.title;
                                toastr.options = {
                                    positionClass: 'toast-top-left',
                                    onclick: null
                                };
                                var $toast = toastr[shortCutFunction](msg, title); // Wire up an event handler to a button in the toast, if it exists
                                $toastlast = $toast;

                            }
                        }
                    });
                }
            });
        });





        $(document).ready(function () {

            $('#datatable-responsive').DataTable( {
                "order": [[ 0, "desc" ]]
            } );

        });


    </script>


@endsection