routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;



Auth::routes();



Route::get('/', 'HomeController@index')->name('home');

//Route::get('lang/{language}', 'LanguageController@switchLang')->name('lang.switch');

Route::group(['prefix' => 'administrator' , 'namespace' => 'Admin'], function () {

    Route::get('/login', 'LoginController@login')->name('admin.login');
    Route::post('/login', 'LoginController@postLogin')->name('admin.postLogin');

    // Password Reset Routes...

    Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('administrator.password.request');
    Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('administrator.password.email');
    Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('administrator.password.reset.token');
    Route::post('password/reset', 'Auth\ResetPasswordController@reset');

});


Route::group(['prefix' => 'administrator', 'namespace' => 'Admin', 'middleware' => ['admin']], function () {

    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/home', 'HomeController@index')->name('admin.home');


    Route::resource('helpAdmin', 'HelpAdminController');
    Route::get('helpAdmin/{id}/delete', 'HelpAdminController@delete')->name('helpAdmin.delete');
    Route::post('helpAdmin/{id}/delete', 'HelpAdminController@deleteHelpAdmin')->name('helpAdmin.message.delete');
    Route::post('helpAdmin/{id}/suspend', 'HelpAdminController@suspendHelpAdmin')->name('helpAdmin.message.suspend');
    Route::get('user/{id}/delete', 'UsersController@delete')->name('user.for.delete');
    Route::post('user/suspend', 'HelpAdminController@suspend')->name('user.suspend');
    // Roles routes ..........
    Route::resource('roles', 'RolesController');
    Route::post('role/delete', 'RolesController@delete')->name('role.delete');


    Route::resource('users', 'UsersController');
    Route::resource('providers_app', 'ProviderController');
    Route::post('providers_app/suspend', 'ProviderController@suspend')->name('providers_app.suspend');
    Route::post('accepted','UsersController@accpetedUser')->name('user.accepted');
    Route::post('refuseUser','UsersController@refuseUser')->name('user.refuseUser');
    Route::post('reAcceptUser','UsersController@reAcceptUser')->name('user.reAcceptUser');
    Route::post('suspendUser','UsersController@suspendUser')->name('user.suspendUser');

    Route::resource('deliveries', 'DeliveryController');
    Route::post('deliveries/accepted','DeliveryController@accpetedUser')->name('deliveries.accepted');
    Route::post('deliveries/refuseUser','DeliveryController@refuseUser')->name('deliveries.refuseUser');

    Route::resource('supplies', 'SuppliesController');
    Route::post('supplies/delete', 'SuppliesController@delete')->name('supplies.delete');
    Route::post('supplies/delete_image', 'SuppliesController@deleteImage')->name('supplies.deleteImage');

    Route::resource('pets', 'PetController');
    Route::resource('plants', 'PlantController');
    Route::post('pets/suspend', 'PetController@suspend')->name('pets.suspend');


    Route::resource('cultural_videos', 'CulturalVideoController');
    Route::post('cultural_videos/suspend', 'CulturalVideoController@suspend')->name('cultural_videos.suspend');
    Route::post('cultural_videos/delete', 'CulturalVideoController@delete')->name('cultural_videos.delete');


    Route::get('public/notifications', 'NotificationsController@publicNotifications')->name('public.notifications');
    Route::get('public/notifications/create', 'NotificationsController@createPublicNotifications')->name('create.public.notifications');

    Route::get('notifications/promo_code', 'NotificationsController@promo_code')->name('notifications_admin.promo_code');
    Route::get('notifications/get_promo_code', 'NotificationsController@get_promo_code')->name('notifications_admin.get_promo_code');
    Route::get('notifications/renderUsesData', 'NotificationsController@renderUsesData')->name('notifications_admin.renderUsesData');
    Route::post('notifications_admin/send_promo_code', 'NotificationsController@send_promo_code')->name('notifications_admin.send_promo_code');
    Route::post('notifications_admin/delete', 'NotificationsController@delete')->name('notifications_admin.delete');

    Route::post('send/public/notifications', 'NotificationsController@sendPublicNotifications')->name('send.public.notifications');


    // --------------------------------------  promo_codes .................
    Route::resource('promo_codes', 'PromoCodesController');
    Route::post('promo_codes/delete', 'PromoCodesController@delete')->name('promo_codes.delete');
    Route::post('promo_codes/suspend', 'PromoCodesController@suspend')->name('promo_codes.suspend');


    Route::get('settings/aboutus', 'SettingsController@aboutus')->name('settings.aboutus');
    Route::get('settings/taxs', 'SettingsController@taxs')->name('settings.taxs');
    Route::get('settings/termsProvider', 'SettingsController@termsGym')->name('settings.termsGym');
    Route::get('settings/terms', 'SettingsController@terms')->name('settings.terms');
    Route::get('settings/suspendElement', 'SettingsController@suspendElement')->name('settings.suspendElement');

    Route::get('/settings/app-general-settings', 'SettingsController@appGeneralSettings')->name('settings.app.general');
    Route::get('settings/contacts', 'SettingsController@contactus')->name('settings.contactus');
    Route::get('settings/minutes_control', 'SettingsController@minutes_control')->name('settings.minutes_control');


    Route::post('/settings', 'SettingsController@store')->name('administrator.settings.store');

//    Route::post('contactus/reply/{id}', 'SupportsController@reply')->name('support.reply');
//    Route::get('contactus', 'SupportsController@index')->name('support.index');
//    Route::get('contactus/{id}', 'SupportsController@show')->name('support.show');
//    Route::post('support/contact/delete', 'SupportsController@delete')->name('support.contact.delete');


//    Route::resource('supports', 'SupportsController');
//    Route::post('supports/delete', 'SupportsController@delete')->name('supports.delete');

//    Route::resource('types', 'TypesSupportController');


    Route::post('city/delete/group', 'CitiesController@groupDelete')->name('cities.group.delete');
    Route::post('cities/delete', 'CitiesController@delete')->name('city.delete');
    Route::resource('cities', 'CitiesController');
    Route::post('city/suspend', 'CitiesController@suspend')->name('city.suspend');

    // -------------------------------------- categories .................
    Route::resource('categories', 'CategoriesController');
    Route::post('categories/delete', 'CategoriesController@delete')->name('categories.delete');
    Route::post('categories/suspend', 'CategoriesController@suspend')->name('categories.suspend');

    Route::resource('reports', 'ReportsController');

    Route::get('/testImageView', 'UsersController@testImageView')->name('Provider.testImageView');
    Route::post('/testImage', 'UsersController@testImage')->name('Provider.testImage');


    Route::resource('banks', 'BanksController');
    Route::post('bank/suspend', 'BanksController@suspend')->name('bank.suspend');

    Route::get('bank-transfer-admin', 'BankTransferController@index')->name('bank-transfer-admin');
    Route::post('accept-transfer-admin', 'BankTransferController@accepted')->name('accept-transfer-admin');
    Route::post('refuse-transfer-admin', 'BankTransferController@refuse')->name('refuse-transfer-admin');

    Route::resource('admin_contact_us_inbox', 'ContactUsController');
    Route::get("admin_reports","ContactUsController@reports")->name("admin.support.reports");
    Route::get('updateIsRead', 'ContactUsController@updateIsRead')->name('admin.support.updateIsRead');
    Route::get('updateIsDeleted', 'ContactUsController@updateIsDeleted')->name('admin.support.updateIsDeleted');
    Route::get('removeAllMessages', 'ContactUsController@removeAllMessages')->name('admin.support.removeAllMessages');


    Route::resource('BankProjects', 'BankProjectsController');
    Route::post('BankProjects/accepted', 'BankProjectsController@accepted')->name('BankProjects.accepted');
    Route::post('BankProjects/refuse', 'BankProjectsController@refuse')->name('BankProjects.refuse');

    Route::resource('reports', 'ReportsController');
    Route::get('provider_data_report', 'ReportsController@gym_data')->name('provider_data_report');

    Route::post('/logout', 'LoginController@logout')->name('administrator.logout');

});



Route::get('/sub', function (Illuminate\Http\Request $request) {

    $cities =\App\Models\City::whereParentId($request->id)->get();

    if (!empty($cities) && count($cities) > 0){
        return response()->json( $cities);
    }else{

        return response()->json(401);
    }


})->name('getSub');



Route::get('roles', function () {

    $user = Auth::guard('master_user')->user();
//    $user->retract('admin');
    $user->assign('*');
    Bouncer::allow('*')->everything();
    $user->allow('users_manage');
});


Route::post('user/update/token', function (Illuminate\Http\Request $request) {

    $user = \App\User::whereId($request->id)->first();

    if ($request->token) {
        $data = \App\Models\Device::where('device', $request->token)->first();
        if ($data) {
            $data->user_id = $user->id;
            $data->save();
        } else {


            $data = new \App\Models\Device;
            $data->device = $request->token;
            $data->user_id = $user->id;
            $data->device_type = 'web';
            $data->save();
        }
    }

})->name('user.update.token');



Route::get('testing',function (){
    $data = [];
    $data[] =  env('DB_DATABASE');
    $data[] =  env('DB_USERNAME');
    $data[] =  env('DB_PASSWORD');

app/Http/Controllers/Admin/DeliveryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\User;
use Illuminate\Http\Request;

class DeliveryController extends Controller
{

    public function index(Request  $request)
    {
        $query = User::select('users.id','name','phone','email','is_accepted','is_suspend','users.created_at')->where('defined_user','delivery');

        if (isset($request->is_accepted)){
            $query->whereIsActiveAndIsAccepted(1,0);
            $pageName  = 'طلبات الإنضمام';
        }else{
            $query->whereIsActiveAndIsAccepted(1,1);
            $pageName  = 'المناديب لدينا';
        }

        $delivery =  $query->join('master_users', 'users.master_user_id', '=', 'master_users.id')->get();

        return view('admin.delivery.index',compact('delivery','pageName'));
    }


    public function create()
    {
        //
    }

    public function store(Request $request)
    {
        //
    }


    public function show($id)
    {
        $user = User::with('master_user','profile')->findOrFail($id);


        return view('admin.delivery.show',compact('user'));
    }


    public function edit($id)
    {
        //
    }


    public function update(Request $request, $id)
    {
        //
    }


    public function destroy($id)
    {
        //
    }

    public function accpetedUser(Request $request){

        $user = User::findOrFail($request->id);

        if ($user){

            $user->update(['is_accepted' => 1]);

            return response()->json( [ 'status' => true  ] , 200 );

        }else{

            return response()->json( [   'status' => false  ] , 200 );
        }
    }


    public function refuseUser(Request $request){
        $user = User::findOrFail($request->id);

        if ($user){
//            $user->delete();
        }
        return response()->json( [  'status' => true , ] , 200 );
    }
}

app/Http/Controllers/Api/Delivery/AuthController.php
<?php

namespace App\Http\Controllers\Api\Delivery;

use App\Http\Controllers\Controller;
use App\Http\Requests\api\Auth\changePassRequest;
use App\Http\Requests\api\Auth\checkActivation;
use App\Http\Requests\api\Auth\checkPhoneOrEmailExist;
use App\Http\Requests\api\Auth\codeExist;
use App\Http\Requests\api\Auth\editUser;
use App\Http\Requests\api\Auth\login;
use App\Http\Requests\api\Auth\resgister;
use App\Http\Requests\api\removeImage;
use App\Http\Requests\api\validImage;
use App\Repositories\AuthRepository;
use App\Traits\RespondsWithHttpStatus;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class AuthController extends Controller
{
    use RespondsWithHttpStatus;
    private $authRepository;

    public function __construct(AuthRepository $authRepository)
    {
        $this->authRepository = $authRepository;

        $this->middleware('auth:api')
            ->only(['changPassword' ,'editProfile' , 'edit_car','removeUser','logOut']);

        $this->middleware('vaildApiToken') ->only(['register' ]);
    }

    public function register(resgister $request){

         $this->authRepository->register($request);

        return $this->success(trans('global.register_in_successfully'));
    }


    public function login(login $request){

        $data =   $this->authRepository->login($request);

        return $this->success(trans('global.logged_in_successfully'),$data);
    }

    public function forgetPassword(checkPhoneOrEmailExist $request){

        $data =    $this->authRepository->forgetPassword($request);

        return $this->success($data['message'],['code' => $data['code'] ] );
    }

    public function resetPassword(checkPhoneOrEmailExist $request){

        $data =    $this->authRepository->resetPassword($request);

        return $this->success($data['message'],$data['data']);
    }

    public function resendCode(codeExist $request){

        $data =    $this->authRepository->resendCode($request);

        return $this->success(trans('global.activation_code_sent'),$data);
    }

    public function checkCodeActivation(checkActivation $request){

        $data =    $this->authRepository->checkCode($request);

        return $this->success(trans('global.your_account_was_activated'),$data);
    }


    public function checkCodeCorrect(checkActivation $request){

        return $this->success('الكود صحيح');
    }


    public function changPassword ( changePassRequest  $request )
    {
        $data =    $this->authRepository->changPassword($request);

        return $this->success($data['message']);
    }


    public function editProfile (editUser $request )
    {
        $data =  $this->authRepository->editProfile($request);

        return $this->success(trans('global.profile_edit_success') , $data);
    }

    public function edit_car(Request $request )
    {
        $data =  $this->authRepository->edit_car_delivery($request);

        return $this->success(trans('global.profile_edit_success') , $data);
    }


    public function logOut(Request $request){

        $this->authRepository->logOut($request);

        return $this->success(trans('global.logged_out_successfully'));
    }

    public function upload(validImage $request){

        $data =  $this->authRepository->uploadImage($request);

        return $this->success('تم رفع الصورة بنجاح',$data);
    }

    public function removeImage(removeImage $request){

        $this->authRepository->removeImage($request);

        return $this->success('تم مسح الصورة بنجاح');
    }

    public function removeUser(Request  $request){

        $user = Auth::user();

        if ($user){
            $user->delete();

            return $this->success('تم مسح المستخدم بنجاح');
        }else{
            return $this->success('لا يابشمهندس البيانات مش صح  😂😂');
        }
    }


}

resources/views/admin/delivery/edit.blade.php
@extends('admin.layouts.master')
@section('title', __('maincp.users_manager'))



@section('styles')


    <style>
        #parsley-id-multiple-roles li{
            position: absolute;
            top: -22px;
            right: 80px;
        }
    </style>

@endsection

@section('content')


    <form method="POST" action="{{ route('users.update', $user->id) }}" enctype="multipart/form-data"
          data-parsley-validate novalidate>
    {{ csrf_field() }}
    {{ method_field('PUT') }}



    <!-- Page-Title -->
        <div class="row">
            <div class="col-sm-12 col-sm-offset-2" >
                <div class="btn-group pull-right m-t-15">
                   {{--  <a href="{{ route('users.create') }}" type="button" class="btn btn-custom waves-effect waves-light"
                       aria-expanded="false"> @lang('maincp.add')
                        <span class="m-l-5">
                        <i class="fa fa-plus"></i>
                    </span>
                    </a> --}}
                </div>
                <h4 class="page-title">@lang('maincp.edit_user_data')</h4>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-8 " >
                <div class="card-box">


                    <h4 class="header-title m-t-0 m-b-30">@lang('maincp.edit_data')</h4>

<div class="row">
                    <div class="col-xs-6">
                        <div class="form-group">
                            <label for="userName">@lang('maincp.full_name')*</label>
                            <input type="text" name="name" value="{{ $user->name or old('name') }}" class="form-control"
                                   required
                                   placeholder="@lang('maincp.full_name')..."
                                   data-parsley-trigger="keyup"
                                   data-parsley-required-message="اسم المستخدم بالكامل مطلوب"
                                   data-parsley-maxlength="55"
                                   data-parsley-pattern="^[a-zA-Z0-9\u0621-\u064A\u0660-\u0669 ]+$"
                                   data-parsley-pattern-message="النظام لا يقبل العلامات الخاصة"
                                   data-parsley-maxlength-message=" أقصى عدد الحروف المسموح بها هى (55) حرف"
                                   />
                            <p class="help-block" id="error_userName"></p>
                            @if($errors->has('name'))
                                <p class="help-block">
                                    {{ $errors->first('name') }}
                                </p>
                            @endif
                        </div>
                    </div>

                    <div class="col-xs-6">
                        <div class="form-group{{ $errors->has('phone') ? ' has-error' : '' }}">
                            <label for="userPhone">@lang('maincp.mobile_number') *</label>
                            <input type="text" name="phone" value="{{ $user->phone or old('phone') }}"
                                   class="form-control numbersOnly  phone" required
                                   placeholder="@lang('maincp.mobile_number') ..."/>
                            @if($errors->has('phone'))
                                <p class="help-block">
                                    {{ $errors->first('phone') }}
                                </p>
                            @endif
                        </div>
                    </div>
                    
                    
                      </div>


                    <div class="col-xs-12">
                        <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                            <label for="emailAddress">@lang('maincp.e_mail') *</label>

                            <input type="email" name="email" data-parsley-trigger="keyup"
                                   value="{{ $user->email or old('email') }}"
                                   class="form-control email" placeholder="@lang('maincp.e_mail')..." required/>
                            @if($errors->has('email'))
                                <p class="help-block">{{ $errors->first('email') }}</p>
                            @endif

                        </div>

                    </div>

                    <div class="col-xs-6">
                        <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
                            <label for="pass1">@lang('maincp.password')*</label>


                            <input type="password" name="password" id="pass1"
                                   class="form-control"
                                   placeholder="@lang('maincp.password')..."
                                   data-parsley-trigger="keyup"
                                   data-parsley-required-message="كلمة المرور مطلوبة"
                                   data-parsley-maxlength="55"
                                   data-parsley-minlength="6"
                                   data-parsley-maxlength-message=" أقصى عدد الحروف المسموح بها هى (55) حرف"
                                   data-parsley-minlength-message=" أقل عدد الحروف المسموح بها هى (6) حرف"
                                   
                            />

                            @if($errors->has('password'))
                                <p class="help-block">{{ $errors->first('password') }}</p>
                            @endif

                        </div>
                    </div>


                    <div class="col-xs-6">
                        <div class="form-group{{ $errors->has('password_confirmation') ? ' has-error' : '' }}">
                            <label for="passWord2">@lang('maincp.confirm_password')*</label>
                            <input data-parsley-equalto="#pass1" name="password_confirmation" type="password"
                                   placeholder="@lang('maincp.confirm_password').."
                                    data-parsley-trigger="keyup"
                                   data-parsley-required-message="تأكيد كلمة المرور مطلوب"
                                   data-parsley-equalto-message="تأكيد كلمة المرور غير متطابقة"
                      
                                   class="form-control">
                            @if($errors->has('password_confirmation'))
                                <p class="help-block">{{ $errors->first('password_confirmation') }}</p>
                            @endif


                        </div>
                    </div>





                    @if(!$user->roles()->whereName('owner')->first() && auth()->id() != $user->id)


                        {{--<div class="form-group{{ $errors->has('roles') ? ' has-error' : '' }}">--}}
                            {{--<label for="passWord2">@lang('maincp.permission') *</label>--}}
                            {{--<select multiple="multiple" class="multi-select" id="my_multi_select1" name="roles[]"--}}
                                    {{--data-plugin="multiselect">--}}
                                {{--@foreach($roles as  $value)--}}

                                    {{--<option value="{{ $value->name }}"--}}
                                            {{--@if($user->roles->pluck('name', 'name')) @foreach($user->roles->pluck('name', 'name') as $roleUser) @if($roleUser == $value->name) selected @endif @endforeach @endif >{{ $value->title }}</option>--}}

                                {{--@endforeach--}}

                            {{--</select>--}}

                            {{--@if($errors->has('roles'))--}}
                                {{--<p class="help-block"> {{ $errors->first('roles') }}</p>--}}
                            {{--@endif--}}

                        {{--</div>--}}


                        <div class="col-xs-12">
                            <label for="passWord2">@lang('maincp.permission') *</label>
                            <div class="form-group{{ $errors->has('roles') ? ' has-error' : '' }}">

                                @foreach($roles as  $value)

                                    <div class="col-sm-4">
                                        <div class="checkbox checkbox-primary">
                                            <input name="roles[]" value="{{ $value->id }}" class="requiredField"
                                                   @if($user->roles->pluck('name', 'name')) @foreach($user->roles->pluck('name', 'name') as $roleUser) @if($roleUser == $value->name) checked @endif @endforeach @endif  required id="checkbox{{ $value->id }}"
                                                   type="checkbox">
                                            <label for="checkbox{{ $value->id }}">
                                                {{ $value->title }}
                                            </label>
                                        </div>
                                    </div>
                                @endforeach
                                @if($errors->has('roles'))
                                    <p class="help-block"> {{ $errors->first('roles') }}</p>
                                @endif



                            </div>
                        </div>






                    @endif




                    <div class="form-group text-right m-t-20">
                        <button class="btn btn-warning waves-effect waves-light m-t-20" type="submit">
                           @lang('maincp.save_data')  
                        </button>
                        <button onclick="window.history.back();return false;" type="reset"
                                class="btn btn-default waves-effect waves-light m-l-5 m-t-20">
                            @lang('maincp.disable') 
                        </button>
                    </div>

                </div>
            </div><!-- end col -->
            
            <div class ="col-sm4">
            
                <div class="card-box" style="overflow: hidden;">
                <h4 class="header-title m-t-0 m-b-30">@lang('institutioncp.personal_image')</h4>
                    <div class="form-group">
                        <div class="col-sm-12">
                    
                            <input type="hidden" value="{{ $user->image }}" name="oldImage"/>
                            <input type="file" name="image" class="dropify" data-max-file-size="6M"
                                        data-default-file="{{ $user->image }}"/>
                    
                        </div>
                    </div>
                </div>
               
            </div>

        </div>
        <!-- end row -->
    </form>

@endsection

@section('scripts')

<script type="text/javascript"
        src="{{ request()->root() }}/public/assets/admin/js/validate-{{ config('app.locale') }}.js"></script>

@endsection