routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;



Auth::routes();



Route::get('/', 'HomeController@index')->name('home');

//Route::get('lang/{language}', 'LanguageController@switchLang')->name('lang.switch');

Route::group(['prefix' => 'administrator' , 'namespace' => 'Admin'], function () {

    Route::get('/login', 'LoginController@login')->name('admin.login');
    Route::post('/login', 'LoginController@postLogin')->name('admin.postLogin');

    // Password Reset Routes...

    Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('administrator.password.request');
    Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('administrator.password.email');
    Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('administrator.password.reset.token');
    Route::post('password/reset', 'Auth\ResetPasswordController@reset');

});


Route::group(['prefix' => 'administrator', 'namespace' => 'Admin', 'middleware' => ['admin']], function () {

    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/home', 'HomeController@index')->name('admin.home');


    Route::resource('helpAdmin', 'HelpAdminController');
    Route::get('helpAdmin/{id}/delete', 'HelpAdminController@delete')->name('helpAdmin.delete');
    Route::post('helpAdmin/{id}/delete', 'HelpAdminController@deleteHelpAdmin')->name('helpAdmin.message.delete');
    Route::post('helpAdmin/{id}/suspend', 'HelpAdminController@suspendHelpAdmin')->name('helpAdmin.message.suspend');
    Route::get('user/{id}/delete', 'UsersController@delete')->name('user.for.delete');
    Route::post('user/suspend', 'HelpAdminController@suspend')->name('user.suspend');
    // Roles routes ..........
    Route::resource('roles', 'RolesController');
    Route::post('role/delete', 'RolesController@delete')->name('role.delete');


    Route::resource('users', 'UsersController');
    Route::resource('providers_app', 'ProviderController');
    Route::post('providers_app/suspend', 'ProviderController@suspend')->name('providers_app.suspend');
    Route::post('accepted','UsersController@accpetedUser')->name('user.accepted');
    Route::post('refuseUser','UsersController@refuseUser')->name('user.refuseUser');
    Route::post('reAcceptUser','UsersController@reAcceptUser')->name('user.reAcceptUser');
    Route::post('suspendUser','UsersController@suspendUser')->name('user.suspendUser');

    Route::resource('deliveries', 'DeliveryController');
    Route::post('deliveries/accepted','DeliveryController@accpetedUser')->name('deliveries.accepted');
    Route::post('deliveries/refuseUser','DeliveryController@refuseUser')->name('deliveries.refuseUser');

    Route::resource('supplies', 'SuppliesController');
    Route::post('supplies/delete', 'SuppliesController@delete')->name('supplies.delete');
    Route::post('supplies/delete_image', 'SuppliesController@deleteImage')->name('supplies.deleteImage');

    Route::resource('pets', 'PetController');
    Route::resource('plants', 'PlantController');
    Route::post('pets/suspend', 'PetController@suspend')->name('pets.suspend');


    Route::resource('cultural_videos', 'CulturalVideoController');
    Route::post('cultural_videos/suspend', 'CulturalVideoController@suspend')->name('cultural_videos.suspend');
    Route::post('cultural_videos/delete', 'CulturalVideoController@delete')->name('cultural_videos.delete');


    Route::get('public/notifications', 'NotificationsController@publicNotifications')->name('public.notifications');
    Route::get('public/notifications/create', 'NotificationsController@createPublicNotifications')->name('create.public.notifications');

    Route::get('notifications/promo_code', 'NotificationsController@promo_code')->name('notifications_admin.promo_code');
    Route::get('notifications/get_promo_code', 'NotificationsController@get_promo_code')->name('notifications_admin.get_promo_code');
    Route::get('notifications/renderUsesData', 'NotificationsController@renderUsesData')->name('notifications_admin.renderUsesData');
    Route::post('notifications_admin/send_promo_code', 'NotificationsController@send_promo_code')->name('notifications_admin.send_promo_code');
    Route::post('notifications_admin/delete', 'NotificationsController@delete')->name('notifications_admin.delete');

    Route::post('send/public/notifications', 'NotificationsController@sendPublicNotifications')->name('send.public.notifications');


    // --------------------------------------  promo_codes .................
    Route::resource('promo_codes', 'PromoCodesController');
    Route::post('promo_codes/delete', 'PromoCodesController@delete')->name('promo_codes.delete');
    Route::post('promo_codes/suspend', 'PromoCodesController@suspend')->name('promo_codes.suspend');


    Route::get('settings/aboutus', 'SettingsController@aboutus')->name('settings.aboutus');
    Route::get('settings/taxs', 'SettingsController@taxs')->name('settings.taxs');
    Route::get('settings/termsProvider', 'SettingsController@termsGym')->name('settings.termsGym');
    Route::get('settings/terms', 'SettingsController@terms')->name('settings.terms');
    Route::get('settings/suspendElement', 'SettingsController@suspendElement')->name('settings.suspendElement');

    Route::get('/settings/app-general-settings', 'SettingsController@appGeneralSettings')->name('settings.app.general');
    Route::get('settings/contacts', 'SettingsController@contactus')->name('settings.contactus');
    Route::get('settings/minutes_control', 'SettingsController@minutes_control')->name('settings.minutes_control');


    Route::post('/settings', 'SettingsController@store')->name('administrator.settings.store');

//    Route::post('contactus/reply/{id}', 'SupportsController@reply')->name('support.reply');
//    Route::get('contactus', 'SupportsController@index')->name('support.index');
//    Route::get('contactus/{id}', 'SupportsController@show')->name('support.show');
//    Route::post('support/contact/delete', 'SupportsController@delete')->name('support.contact.delete');


//    Route::resource('supports', 'SupportsController');
//    Route::post('supports/delete', 'SupportsController@delete')->name('supports.delete');

//    Route::resource('types', 'TypesSupportController');


    Route::post('city/delete/group', 'CitiesController@groupDelete')->name('cities.group.delete');
    Route::post('cities/delete', 'CitiesController@delete')->name('city.delete');
    Route::resource('cities', 'CitiesController');
    Route::post('city/suspend', 'CitiesController@suspend')->name('city.suspend');

    // -------------------------------------- categories .................
    Route::resource('categories', 'CategoriesController');
    Route::post('categories/delete', 'CategoriesController@delete')->name('categories.delete');
    Route::post('categories/suspend', 'CategoriesController@suspend')->name('categories.suspend');

    Route::resource('reports', 'ReportsController');

    Route::get('/testImageView', 'UsersController@testImageView')->name('Provider.testImageView');
    Route::post('/testImage', 'UsersController@testImage')->name('Provider.testImage');


    Route::resource('banks', 'BanksController');
    Route::post('bank/suspend', 'BanksController@suspend')->name('bank.suspend');

    Route::get('bank-transfer-admin', 'BankTransferController@index')->name('bank-transfer-admin');
    Route::post('accept-transfer-admin', 'BankTransferController@accepted')->name('accept-transfer-admin');
    Route::post('refuse-transfer-admin', 'BankTransferController@refuse')->name('refuse-transfer-admin');

    Route::resource('admin_contact_us_inbox', 'ContactUsController');
    Route::get("admin_reports","ContactUsController@reports")->name("admin.support.reports");
    Route::get('updateIsRead', 'ContactUsController@updateIsRead')->name('admin.support.updateIsRead');
    Route::get('updateIsDeleted', 'ContactUsController@updateIsDeleted')->name('admin.support.updateIsDeleted');
    Route::get('removeAllMessages', 'ContactUsController@removeAllMessages')->name('admin.support.removeAllMessages');


    Route::resource('BankProjects', 'BankProjectsController');
    Route::post('BankProjects/accepted', 'BankProjectsController@accepted')->name('BankProjects.accepted');
    Route::post('BankProjects/refuse', 'BankProjectsController@refuse')->name('BankProjects.refuse');

    Route::resource('reports', 'ReportsController');
    Route::get('provider_data_report', 'ReportsController@gym_data')->name('provider_data_report');

    Route::post('/logout', 'LoginController@logout')->name('administrator.logout');

});



Route::get('/sub', function (Illuminate\Http\Request $request) {

    $cities =\App\Models\City::whereParentId($request->id)->get();

    if (!empty($cities) && count($cities) > 0){
        return response()->json( $cities);
    }else{

        return response()->json(401);
    }


})->name('getSub');



Route::get('roles', function () {

    $user = Auth::guard('master_user')->user();
//    $user->retract('admin');
    $user->assign('*');
    Bouncer::allow('*')->everything();
    $user->allow('users_manage');
});


Route::post('user/update/token', function (Illuminate\Http\Request $request) {

    $user = \App\User::whereId($request->id)->first();

    if ($request->token) {
        $data = \App\Models\Device::where('device', $request->token)->first();
        if ($data) {
            $data->user_id = $user->id;
            $data->save();
        } else {


            $data = new \App\Models\Device;
            $data->device = $request->token;
            $data->user_id = $user->id;
            $data->device_type = 'web';
            $data->save();
        }
    }

})->name('user.update.token');



Route::get('testing',function (){
    $data = [];
    $data[] =  env('DB_DATABASE');
    $data[] =  env('DB_USERNAME');
    $data[] =  env('DB_PASSWORD');

app/Models/Category.php
<?php

namespace App\Models;

use App\Traits\CanBeScoped;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use  CanBeScoped;
    protected $guarded = [];


    public function children()
    {
        return $this->hasMany(Category::class, 'parent_id');
    }


    public function parent(){
        return $this->belongsTo(Category::class,'parent_id');
    }

}

app/Http/Controllers/Admin/CategoriesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Category;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Gate;
use Validator;
use UploadImage;


class CategoriesController extends Controller
{

    public $public_path;

    public function __construct()
    {
        $this->public_path = 'files/categories/';
    }

    public function index(Request $request)
    {

	     $categories = Category::where('parent_id','!=', 0)->latest()->get();
	     $pageName = 'إدارة الاقسام  ';

        return view('admin.categories.index',compact('categories','pageName'));
    }
    public function create()
    {
	   $cats = Category::whereParentId(0)->where('is_suspend',0)->get();

	    $pageName = '   اسم  القسم او المستلزم';

        return view('admin.categories.create')->with(compact('cats','pageName'));
    }

    public function store(Request $request)
    {

        $category = new Category;
        $category->name_ar = $request->name_ar;
        $category->parent_id = $request->parentId ;

//        if ($request->hasFile('image')):
//            $category->image =  $this->public_path . UploadImage::uploadImage($request, 'image', $this->public_path);
//        endif;

        if ($category->save()) {
            return response()->json([
                'status' => true,
                "message" => __('trans.addingSuccess',['itemName' => "القسم"]),
                "url" =>  route('categories.index'),

            ]);
        }

    }


    public function show($id)
    {
        //
    }


    public function edit($id)
    {
        $cats = Category::whereParentId(0)->where('is_suspend',0)->get();

        $category = Category::findOrFail($id);

        $pageName = '   اسم القسم ';
        return view('admin.categories.edit')->with(compact('category', 'cats', 'pageName' ));
    }


    public function update(Request $request, $id)
    {
        $category = Category::findOrFail($id);
        $category->name_ar = $request->name_ar;
        $category->parent_id = $request->parentId ;

//        if ($request->hasFile('image')):
//            $category->image =     $this->public_path . UploadImage::uploadImage($request, 'image', $this->public_path);
//        endif;

        if ($category->save()) {
            return response()->json([
                'status' => true,
                "message" => __('trans.editSuccess',['itemName' => "القسم"]),
                "url" =>  route('categories.index'),
            ]);
        }

    }



       public function delete(Request $request){
	    if (!Gate::allows('settings_manage')) {
		 return abort(401);
	    }

	    $model = Category::findOrFail($request->id);

	    if (count($model->product) > 0) {

		 return response()->json([
		         'status' => false,
		         'message' => "عفواً, لا يمكنك حذف التخصص نظراً لوجود منتجات  فيها"
		 ]);
	    }


	    if ($model->delete()) {
            $model->deleteTranslations();
		 return response()->json([
		         'status' => true,
		         'data' => $model->id
		 ]);
	    }

       }

       public function suspend(Request $request)
       {
	    $model = Category::findOrFail($request->id);
	    $model->is_suspend = $request->type;
	    if ($request->type == 1) {

            $message = "لقد تم حظر القسم بنجاح";
	    } else {
            $message = "لقد تم فك الحظر على القسم بنجاح";
	    }
//	    if (count($model->users) > 0) {
//		 return response()->json([
//		         'status' => false,
//		         'message' => 'عفواً, لا يمكنك حظر القسم نظراً لوجود مستخدمين مشتركين فيها'
//		 ]);
//	    }
//
//	    if (count($model->product) > 0) {
//
//		 return response()->json([
//		         'status' => false,
//		         'message' => "عفواً, لا يمكنك حذف القسم نظراً لوجود منتجات  فيها"
//		 ]);
//	    }

	    if ($model->save()) {
		 return response()->json([
		         'status' => true,
		         'message' => $message,
		         'id' => $request->id,
		         'type' => $request->type

		 ]);
	    }

       }



}

resources/views/admin/categories/create.blade.php
@extends('admin.layouts.master')
@section('title', __('maincp.users_manager'))


@section('styles')



@endsection
@section('content')



    <form method="POST" action="{{ route('categories.store') }}@if(request('type')  == 'subcategories' )?type=subcategories @endif" enctype="multipart/form-data"
          data-parsley-validate novalidate>
    {{ csrf_field() }}

    <!-- Page-Title -->
        <div class="row">
            <div class="col-lg-12  ">
                <div class="btn-group pull-right m-t-15">
                    <button type="button" class="btn btn-custom  waves-effect waves-light"
                            onclick="window.history.back();return false;"> رجوع <span class="m-l-5"><i
                                    class="fa fa-reply"></i></span>
                    </button>
                </div>
                <h4 class="page-title">إدارة {{$pageName}}</h4>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12  ">
                <div class="card-box">


                    <h4 class="header-title m-t-0 m-b-30"> إضافة {{$pageName}}</h4>

                    <div class="row">

{{--                        @if(request('type'))--}}
                            <div class="col-xs-6">
                                <div class="form-group">
                                    <label for="userName">إسم القسم الرئيسي*</label>
                                    <select name="parentId" id="" class="form-control requiredFieldWithMaxLenght" required>
                                        <option value="" selected disabled=""> إختر القسم</option>
                                        @foreach($cats as $value)
                                            <option value="{{ $value->id }}">{{ $value->name_ar }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
{{--                        @endif--}}


                        <div class="col-xs-6">
                            <div class="form-group">
                                <label for="userName"> {{$pageName}}      </label>
                                <input type="text" name="name_ar"
                                       class="form-control requiredFieldWithMaxLenght"
                                       required
                                       placeholder="   باللغة العربية{{$pageName}}  ..."/>
                                <p class="help-block" id="error_userName"></p>
                                @if($errors->has('name_ar'))
                                    <p class="help-block">
                                        {{ $errors->first('name_ar') }}
                                    </p>
                                @endif
                            </div>
                        </div>

{{--                        <div class="col-xs-6">--}}
{{--                            <div class="form-group">--}}
{{--                                <label for="userName"> {{$pageName}}   باللغة الإنجليزية</label>--}}
{{--                                <input type="text" name="name_en"--}}
{{--                                       class="form-control requiredFieldWithMaxLenght"--}}
{{--                                       required--}}
{{--                                       placeholder="   باللغة الإنجليزية {{$pageName}}  ..."/>--}}
{{--                                <p class="help-block" id="error_userName"></p>--}}
{{--                                @if($errors->has('name_en'))--}}
{{--                                    <p class="help-block">--}}
{{--                                        {{ $errors->first('name_en') }}--}}
{{--                                    </p>--}}
{{--                                @endif--}}
{{--                            </div>--}}
{{--                        </div>--}}

{{--                        <div class="col-xs-6">--}}
{{--                            <div class="form-group">--}}
{{--                                <label for="usernames">صورة التخصص  *</label>--}}
{{--                                <input type="file" name="image" class="dropify" data-max-file-size="6M"/>--}}
{{--                            </div>--}}

{{--                        </div>--}}



                    </div>


                    <div class="form-group text-right m-t-20">
                        <button class="btn btn-warning waves-effect waves-light m-t-20" type="submit">
                            @lang('maincp.save_data')
                        </button>
                        <button onclick="window.history.back();return false;" type="reset"
                                class="btn btn-default waves-effect waves-light m-l-5 m-t-20">
                            @lang('maincp.disable')
                        </button>
                    </div>

                </div>
            </div><!-- end col -->


        </div>
        <!-- end row -->
    </form>

@endsection



@section('scripts')
    <script type="text/javascript"
            src="{{ request()->root() }}/public/assets/admin/js/validate-{{ config('app.locale') }}.js"></script>
    <script type="text/javascript">

        function validImages() {

            var images = $( "input[name='image']" ).val();


            if ( images === undefined || images == ""   ) {
                var shortCutFunction = 'error';
                var msg = 'من فضلك إختار   صورة واحدة علي الأقل  ';
                var title = 'نجاح';
                toastr.options = {
                    positionClass: 'toast-top-left',
                    preventDuplicates: true,
                    onclick: null
                };
                var $toast = toastr[shortCutFunction](msg, title);
                $toastlast = $toast;
                return false;
            }

            return true;
        }


        $('form').on('submit', function (e) {

            e.preventDefault();

            var formData = new FormData(this);

            var form = $(this);
            form.parsley().validate();

            // if (form.parsley().isValid() && validImages()){
            if (form.parsley().isValid()  ){
                $('.loading').show();

                $.ajax({
                    type: 'POST',
                    url: $(this).attr('action'),
                    data: formData,
                    cache: false,
                    contentType: false,
                    processData: false,
                    success: function (data) {
                        $('.loading').hide();
                        // $('form').trigger("reset");
                        console.log(data);

                        var shortCutFunction = 'success';
                        var msg = data.message;
                        var title = 'نجاح';
                        toastr.options = {
                            positionClass: 'toast-top-left',
                            onclick: null
                        };
                        var $toast = toastr[shortCutFunction](msg, title); // Wire up an event handler to a button in the toast, if it exists
                        $toastlast = $toast;
                        setTimeout(function () {
                            window.location.href = data.url;
                        }, 2000);
                    },
                    error: function (data) {
                    }
                });
            }else {
                $('.loading').hide();
            }
        });

    </script>
@endsection

resources/views/admin/categories/edit.blade.php
@extends('admin.layouts.master')
@section('title', __('maincp.users_manager'))


@section('styles')



@endsection
@section('content')


    <form method="POST" action="{{ route('categories.update', $category->id) }}" enctype="multipart/form-data"
          data-parsley-validate novalidate>
    {{ csrf_field() }}
    {{ method_field('PUT') }}


    <!-- Page-Title -->
        <div class="row">
            <div class="col-lg-12 ">
                <div class="btn-group pull-right m-t-15">
                    <button type="button" class="btn btn-custom  waves-effect waves-light"
                            onclick="window.history.back();return false;"> رجوع <span class="m-l-5"><i
                                    class="fa fa-reply"></i></span>
                    </button>
                </div>
                <h4 class="page-title">إسم {{$pageName}}</h4>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12 ">
                <div class="card-box">


                    <h4 class="header-title m-t-0 m-b-30">تعديل {{$pageName}}</h4>

                    <div class="row">

{{--                        @if(request('type'))--}}
                            <div class="col-xs-6">
                                <div class="form-group">
                                    <label for="userName">إسم القسم*</label>
                                    <select name="parentId"  class="form-control requiredFieldWithMaxLenght" required>
                                        <option value="" selected disabled="">إختر القسم</option>
                                        @foreach($cats as $value)
                                            <option value="{{ $value->id }}" @if($value->id == $category->parent_id) selected @endif>
                                                {{ $value->name_ar }}
                                            </option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
{{--                        @endif--}}



                            <div class="col-xs-6">
                                <div class="form-group">
                                    <label for="userName"> {{$pageName}}      </label>
                                    <input type="text" name="name_ar"
                                           class="form-control requiredFieldWithMaxLenght"
                                           required value="{{ $category->name_ar}}"
                                           placeholder="   باللغة العربية{{$pageName}}  ..."/>
                                    <p class="help-block" id="error_userName"></p>
                                    @if($errors->has('name_ar'))
                                        <p class="help-block">
                                            {{ $errors->first('name_ar') }}
                                        </p>
                                    @endif
                                </div>
                            </div>

{{--                            <div class="col-xs-6">--}}
{{--                                <div class="form-group">--}}
{{--                                    <label for="userName"> {{$pageName}}   باللغة الإنجليزية</label>--}}
{{--                                    <input type="text" name="name_en" value="{{optional($category->translate('en'))->name}}"--}}
{{--                                           class="form-control requiredFieldWithMaxLenght"--}}
{{--                                           required--}}
{{--                                           placeholder="   باللغة الإنجليزية {{$pageName}}  ..."/>--}}
{{--                                    <p class="help-block" id="error_userName"></p>--}}
{{--                                    @if($errors->has('name_en'))--}}
{{--                                        <p class="help-block">--}}
{{--                                            {{ $errors->first('name_en') }}--}}
{{--                                        </p>--}}
{{--                                    @endif--}}
{{--                                </div>--}}
{{--                            </div>--}}

                            <div class="col-xs-4">


{{--                                <div class="form-group">--}}
{{--                                    <label for="usernames">صورة التخصص *</label>--}}


{{--                                    <input type="hidden" value="{{ $category->image }}" name="oldImage"/>--}}
{{--                                    <input type="file" name="image" class="dropify" data-max-file-size="6M"--}}
{{--                                           data-default-file="{{ request()->root().$category->image }}"/>--}}


{{--                                </div>--}}


                            </div>





                        <!-- end col -->
                    </div>


                    <div class="form-group text-right m-t-20">
                        <button class="btn btn-warning waves-effect waves-light m-t-20" type="submit">
                            @lang('maincp.save_data')
                        </button>
                        <button onclick="window.history.back();return false;" type="reset"
                                class="btn btn-default waves-effect waves-light m-l-5 m-t-20">
                            @lang('maincp.disable')
                        </button>
                    </div>

                </div>
            </div><!-- end col -->


        </div>
        <!-- end row -->
    </form>

@endsection



@section('scripts')

    <script type="text/javascript"
            src="{{ request()->root() }}/public/assets/admin/js/validate-{{ config('app.locale') }}.js"></script>

    <script type="text/javascript">
        function validImages() {

            var images = $( "input[name='oldImage']" ).val();


            if ( images === undefined || images == ""   ) {
                var shortCutFunction = 'error';
                var msg = 'من فضلك إختار   صورة واحدة علي الأقل  ';
                var title = 'نجاح';
                toastr.options = {
                    positionClass: 'toast-top-left',
                    preventDuplicates: true,
                    onclick: null
                };
                var $toast = toastr[shortCutFunction](msg, title);
                $toastlast = $toast;
                return false;
            }

            return true;
        }

        $('form').on('submit', function (e) {

            e.preventDefault();

            var formData = new FormData(this);

            var form = $(this);

            form.parsley().validate();

            // if (form.parsley().isValid() && validImages()){
            if (form.parsley().isValid()  ){
                $('.loading').show();

                $.ajax({
                    type: 'POST',
                    url: $(this).attr('action'),
                    data: formData,
                    cache: false,
                    contentType: false,
                    processData: false,
                    success: function (data) {
                        $('.loading').hide();

                        // $('form').trigger("reset");

                        var shortCutFunction = 'success';
                        var msg = data.message;
                        var title = 'نجاح';
                        toastr.options = {
                            positionClass: 'toast-top-left',
                            onclick: null
                        };
                        var $toast = toastr[shortCutFunction](msg, title); // Wire up an event handler to a button in the toast, if it exists
                        $toastlast = $toast;
                        setTimeout(function () {


                            window.location.href = data.url;
                        }, 2000);
                    },
                    error: function (data) {

                    }
                });

            }


        });

    </script>
@endsection